"""Add order_index to criteria and make description nullable

Revision ID: d27b61e3d79a
Revises: c1a2b3d4e5f6
Create Date: 2025-11-24 22:10:41.107191+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd27b61e3d79a'
down_revision: Union[str, Sequence[str], None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('verification_tokens_identifier_token_key'), table_name='verification_tokens')
    op.drop_index(op.f('verification_tokens_token_key'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('sessions_session_token_key'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('accounts_provider_provider_account_id_key'), table_name='accounts')
    op.drop_table('accounts')
    op.alter_column('assessment_documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('assessment_documents_assessment_id_fkey'), 'assessment_documents', type_='foreignkey')
    op.drop_constraint(op.f('assessment_documents_bucket_id_fkey'), 'assessment_documents', type_='foreignkey')
    op.create_foreign_key(None, 'assessment_documents', 'assessments', ['assessment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assessment_documents', 'buckets', ['bucket_id'], ['id'])
    op.alter_column('assessment_results', 'ai_response_raw',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('assessment_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('assessment_results_assessment_id_fkey'), 'assessment_results', type_='foreignkey')
    op.drop_constraint(op.f('assessment_results_criteria_id_fkey'), 'assessment_results', type_='foreignkey')
    op.create_foreign_key(None, 'assessment_results', 'assessments', ['assessment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assessment_results', 'criteria', ['criteria_id'], ['id'])
    op.alter_column('assessments', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('assessments_created_by_fkey'), 'assessments', type_='foreignkey')
    op.drop_constraint(op.f('assessments_workflow_id_fkey'), 'assessments', type_='foreignkey')
    op.drop_constraint(op.f('assessments_organization_id_fkey'), 'assessments', type_='foreignkey')
    op.create_foreign_key(None, 'assessments', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'assessments', 'workflows', ['workflow_id'], ['id'])
    op.create_foreign_key(None, 'assessments', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('audit_logs', 'action_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('audit_logs_organization_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('buckets', 'required',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('buckets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('buckets_workflow_id_fkey'), 'buckets', type_='foreignkey')
    op.create_foreign_key(None, 'buckets', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.add_column('criteria', sa.Column('order_index', sa.Integer(), nullable=True))
    op.alter_column('criteria', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('criteria', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('criteria_workflow_id_fkey'), 'criteria', type_='foreignkey')
    op.create_foreign_key(None, 'criteria', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.alter_column('organizations', 'subscription_tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'trial'::character varying"))
    op.alter_column('organizations', 'subscription_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'trial'::character varying"))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_organization_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('workflows', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('workflows', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflows', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('workflows_organization_id_fkey'), 'workflows', type_='foreignkey')
    op.drop_constraint(op.f('workflows_created_by_fkey'), 'workflows', type_='foreignkey')
    op.create_foreign_key(None, 'workflows', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'workflows', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.create_foreign_key(op.f('workflows_created_by_fkey'), 'workflows', 'users', ['created_by'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(op.f('workflows_organization_id_fkey'), 'workflows', 'organizations', ['organization_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('workflows', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflows', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflows', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_organization_id_fkey'), 'users', 'organizations', ['organization_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'subscription_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'trial'::character varying"))
    op.alter_column('organizations', 'subscription_tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'trial'::character varying"))
    op.drop_constraint(None, 'criteria', type_='foreignkey')
    op.create_foreign_key(op.f('criteria_workflow_id_fkey'), 'criteria', 'workflows', ['workflow_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('criteria', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('criteria', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('criteria', 'order_index')
    op.drop_constraint(None, 'buckets', type_='foreignkey')
    op.create_foreign_key(op.f('buckets_workflow_id_fkey'), 'buckets', 'workflows', ['workflow_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('buckets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('buckets', 'required',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_organization_id_fkey'), 'audit_logs', 'organizations', ['organization_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'action_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.create_foreign_key(op.f('assessments_organization_id_fkey'), 'assessments', 'organizations', ['organization_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('assessments_workflow_id_fkey'), 'assessments', 'workflows', ['workflow_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('assessments_created_by_fkey'), 'assessments', 'users', ['created_by'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('assessments', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'assessment_results', type_='foreignkey')
    op.drop_constraint(None, 'assessment_results', type_='foreignkey')
    op.create_foreign_key(op.f('assessment_results_criteria_id_fkey'), 'assessment_results', 'criteria', ['criteria_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('assessment_results_assessment_id_fkey'), 'assessment_results', 'assessments', ['assessment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('assessment_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('assessment_results', 'ai_response_raw',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'assessment_documents', type_='foreignkey')
    op.drop_constraint(None, 'assessment_documents', type_='foreignkey')
    op.create_foreign_key(op.f('assessment_documents_bucket_id_fkey'), 'assessment_documents', 'buckets', ['bucket_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('assessment_documents_assessment_id_fkey'), 'assessment_documents', 'assessments', ['assessment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('assessment_documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('accounts',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider_account_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('accounts_user_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey'))
    )
    op.create_index(op.f('accounts_provider_provider_account_id_key'), 'accounts', ['provider', 'provider_account_id'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('session_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sessions_user_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_pkey'))
    )
    op.create_index(op.f('sessions_session_token_key'), 'sessions', ['session_token'], unique=True)
    op.create_table('verification_tokens',
    sa.Column('identifier', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False)
    )
    op.create_index(op.f('verification_tokens_token_key'), 'verification_tokens', ['token'], unique=True)
    op.create_index(op.f('verification_tokens_identifier_token_key'), 'verification_tokens', ['identifier', 'token'], unique=True)
    # ### end Alembic commands ###
