#!/usr/bin/env python3
"""
Seed test data for pytest test suite.

This script populates the qteria-test database with:
- 2 test organizations (Org A, Org B)
- 6 test users (admins, process managers, and project handlers for each org)

Run this script ONCE after creating the test database schema.

Usage:
    # Activate venv first
    python scripts/seed_test_data.py
"""
import sys
from pathlib import Path

# Add parent directory to path so we can import app modules
sys.path.insert(0, str(Path(__file__).parent.parent))

from uuid import UUID
from dotenv import load_dotenv
from app.models.base import SessionLocal
from app.models import Organization, User
from app.models.enums import UserRole

# Import test IDs from conftest (these UUIDs are used in JWT tokens during tests)
from tests.conftest import (
    TEST_ORG_A_ID,
    TEST_ORG_B_ID,
    TEST_USER_A_ID,
    TEST_USER_B_ID,
    TEST_USER_A_PM_ID,
    TEST_USER_B_PM_ID,
    TEST_USER_A_PH_ID,
    TEST_USER_B_PH_ID,
)

# Convert string UUIDs to UUID objects
ORG_A_UUID = UUID(TEST_ORG_A_ID)
ORG_B_UUID = UUID(TEST_ORG_B_ID)
USER_A_UUID = UUID(TEST_USER_A_ID)
USER_B_UUID = UUID(TEST_USER_B_ID)
USER_A_PM_UUID = UUID(TEST_USER_A_PM_ID)
USER_B_PM_UUID = UUID(TEST_USER_B_PM_ID)
USER_A_PH_UUID = UUID(TEST_USER_A_PH_ID)
USER_B_PH_UUID = UUID(TEST_USER_B_PH_ID)


def seed_test_data():
    """
    Idempotent test data seeding for pytest.

    Uses PostgreSQL ON CONFLICT DO NOTHING to ensure the script can be run
    multiple times without errors. This allows:
    - Running tests without manual cleanup
    - Seeding empty database
    - Seeding database with partial data (e.g., only org_a exists)
    - Seeding database with all data (no-op, exits quickly)

    The UUIDs match those used in JWT tokens generated by test fixtures.
    """
    # Load test environment
    load_dotenv(".env.test", override=True)

    db = SessionLocal()

    try:
        print("Seeding test organizations (idempotent)...")

        # Use PostgreSQL ON CONFLICT DO NOTHING for idempotent inserts
        from sqlalchemy.dialects.postgresql import insert

        # Seed organizations
        org_data = [
            {
                "id": ORG_A_UUID,
                "name": "Test Organization A",
                "subscription_tier": "trial",
                "subscription_status": "trial",
            },
            {
                "id": ORG_B_UUID,
                "name": "Test Organization B",
                "subscription_tier": "trial",
                "subscription_status": "trial",
            },
        ]

        stmt = insert(Organization).values(org_data).on_conflict_do_nothing(index_elements=["id"])
        result = db.execute(stmt)
        orgs_inserted = result.rowcount

        print(
            f"✅ Organizations: {orgs_inserted} inserted, {len(org_data) - orgs_inserted} already existed"
        )

        print("\nSeeding test users (idempotent)...")

        # Seed users
        user_data = [
            {
                "id": USER_A_UUID,
                "organization_id": ORG_A_UUID,
                "email": "admin@test-org-a.com",
                "name": "Admin User A",
                "role": UserRole.ADMIN,
            },
            {
                "id": USER_A_PM_UUID,
                "organization_id": ORG_A_UUID,
                "email": "pm@test-org-a.com",
                "name": "Process Manager A",
                "role": UserRole.PROCESS_MANAGER,
            },
            {
                "id": USER_A_PH_UUID,
                "organization_id": ORG_A_UUID,
                "email": "ph@test-org-a.com",
                "name": "Project Handler A",
                "role": UserRole.PROJECT_HANDLER,
            },
            {
                "id": USER_B_UUID,
                "organization_id": ORG_B_UUID,
                "email": "admin@test-org-b.com",
                "name": "Admin User B",
                "role": UserRole.ADMIN,
            },
            {
                "id": USER_B_PM_UUID,
                "organization_id": ORG_B_UUID,
                "email": "pm@test-org-b.com",
                "name": "Process Manager B",
                "role": UserRole.PROCESS_MANAGER,
            },
            {
                "id": USER_B_PH_UUID,
                "organization_id": ORG_B_UUID,
                "email": "ph@test-org-b.com",
                "name": "Project Handler B",
                "role": UserRole.PROJECT_HANDLER,
            },
        ]

        stmt = insert(User).values(user_data).on_conflict_do_nothing(index_elements=["id"])
        result = db.execute(stmt)
        users_inserted = result.rowcount

        print(
            f"✅ Users: {users_inserted} inserted, {len(user_data) - users_inserted} already existed"
        )

        db.commit()

        print("\n✅ Test data seeded successfully (idempotent)!")
        print("\nYou can now run tests:")
        print("   pytest tests/test_workflow_api.py -v")

    except Exception as e:
        db.rollback()
        print(f"\n❌ Error seeding test data: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    print("=" * 60)
    print("Seeding Test Data for qteria-test Database")
    print("=" * 60)
    print()
    seed_test_data()
