#!/usr/bin/env python3
"""
Seed test data for pytest test suite.

This script populates the qteria-test database with:
- 2 test organizations (Org A, Org B)
- 4 test users (process managers and admins for each org)

Run this script ONCE after creating the test database schema.

Usage:
    # Activate venv first
    python scripts/seed_test_data.py
"""
import sys
from pathlib import Path

# Add parent directory to path so we can import app modules
sys.path.insert(0, str(Path(__file__).parent.parent))

from uuid import UUID
from dotenv import load_dotenv
from app.models.base import SessionLocal
from app.models import Organization, User
from app.models.enums import UserRole

# Import test IDs from conftest (these UUIDs are used in JWT tokens during tests)
from tests.conftest import (
    TEST_ORG_A_ID,
    TEST_ORG_B_ID,
    TEST_USER_A_ID,
    TEST_USER_B_ID,
)

# Convert string UUIDs to UUID objects
ORG_A_UUID = UUID(TEST_ORG_A_ID)
ORG_B_UUID = UUID(TEST_ORG_B_ID)
USER_A_UUID = UUID(TEST_USER_A_ID)
USER_B_UUID = UUID(TEST_USER_B_ID)


def seed_test_data():
    """
    Seed test organizations and users for pytest.

    This creates the foundational data needed for workflow API tests to pass.
    The UUIDs match those used in JWT tokens generated by test fixtures.
    """
    # Load test environment
    load_dotenv(".env.test", override=True)

    db = SessionLocal()

    try:
        # Check if data already exists
        existing_org = db.query(Organization).filter_by(id=ORG_A_UUID).first()
        if existing_org:
            print("⚠️  Test data already exists. Skipping seed.")
            print("   To re-seed, first run: python scripts/clear_test_data.py")
            return

        print("Creating test organizations...")

        # Create 2 test organizations
        org_a = Organization(
            id=ORG_A_UUID,
            name="Test Organization A",
            subscription_tier="trial",
            subscription_status="trial",
        )

        org_b = Organization(
            id=ORG_B_UUID,
            name="Test Organization B",
            subscription_tier="trial",
            subscription_status="trial",
        )

        db.add(org_a)
        db.add(org_b)
        db.flush()

        print("✅ Created 2 test organizations")
        print(f"   - {org_a.name} ({org_a.id})")
        print(f"   - {org_b.name} ({org_b.id})")

        print("\nCreating test users...")

        # Create test users for Organization A
        user_a_admin = User(
            id=USER_A_UUID,
            organization_id=ORG_A_UUID,
            email="admin@test-org-a.com",
            name="Admin User A",
            role=UserRole.ADMIN,
        )

        user_a_pm = User(
            organization_id=ORG_A_UUID,
            email="pm@test-org-a.com",
            name="Process Manager A",
            role=UserRole.PROCESS_MANAGER,
        )

        # Create test users for Organization B
        user_b_admin = User(
            id=USER_B_UUID,
            organization_id=ORG_B_UUID,
            email="admin@test-org-b.com",
            name="Admin User B",
            role=UserRole.ADMIN,
        )

        user_b_pm = User(
            organization_id=ORG_B_UUID,
            email="pm@test-org-b.com",
            name="Process Manager B",
            role=UserRole.PROCESS_MANAGER,
        )

        db.add_all([user_a_admin, user_a_pm, user_b_admin, user_b_pm])
        db.commit()

        print("✅ Created 4 test users")
        print(f"   - {user_a_admin.name} ({user_a_admin.email}) - {user_a_admin.role}")
        print(f"   - {user_a_pm.name} ({user_a_pm.email}) - {user_a_pm.role}")
        print(f"   - {user_b_admin.name} ({user_b_admin.email}) - {user_b_admin.role}")
        print(f"   - {user_b_pm.name} ({user_b_pm.email}) - {user_b_pm.role}")

        print("\n✅ Test data seeded successfully!")
        print("\nYou can now run tests:")
        print("   pytest tests/test_workflow_api.py -v")

    except Exception as e:
        db.rollback()
        print(f"\n❌ Error seeding test data: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    print("=" * 60)
    print("Seeding Test Data for qteria-test Database")
    print("=" * 60)
    print()
    seed_test_data()
